{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/89/comments/67981192.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/diff/mjmm13/segway_python23:9c8e481cfdd3..50c798f683cf?path=segway%2Fcluster%2F__init__.py"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/89/_/diff#comment-67981192"}}, "parent": {"id": 67980562, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/89/comments/67980562.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/89/_/diff#comment-67980562"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 89, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/89.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/89"}}, "title": "Python 3 Compatibility"}, "content": {"raw": "No this prints the log line after the jobs have finished. If viterbi runs an extra iteration it would be logged second, despite being called first. Printing after every iteration could get you a log file like this\n\njobid\tjobname\tprog\tnum\\_segs\tnum\\_frames\tmaxvmem\tcpu\texit\\_status  \n1165846\tvit0.identifydir-seg.959d9cbe748611e885bbbc305bf153a8\t  \n1165847\tjt0.identifydir-seg.959d9cbe748611e885bbbc305bf153a8\t  \n1165846\tvit0.identifydir-seg.959d9cbe748611e885bbbc305bf153a8\t  \n1165847\tjt0.identifydir-seg.959d9cbe748611e885bbbc305bf153a8\t\n\n1165847\tjt0.identifydir-seg.959d9cbe748611e885bbbc305bf153a8\tgmtkJT\t2\t8000\t1104023552.0000\t2.2897\t0  \n1165846\tvit0.identifydir-seg.959d9cbe748611e885bbbc305bf153a8\t  \n1165846\tvit0.identifydir-seg.959d9cbe748611e885bbbc305bf153a8\tgmtkViterbi\t2\t8000\t1823936512.0000\t2.0807\t0\n\nBecause Viterbi ran an extra time, its full log line appears after. This behaviour was happening in both python 2 and 3, I was never able to figure out why it only started now though and not before the conversion began.", "markup": "markdown", "html": "<p>No this prints the log line after the jobs have finished. If viterbi runs an extra iteration it would be logged second, despite being called first. Printing after every iteration could get you a log file like this</p>\n<p>jobid   jobname prog    num_segs   num_frames maxvmem cpu exit_status<br />\n<a href=\"#!/hoffmanlab/segway/commits/1165846\" rel=\"nofollow\" class=\"ap-connect-link\">1165846</a> vit0.identifydir-seg.<a href=\"#!/hoffmanlab/segway/commits/959d9cbe748611e885bbbc305bf153a8\" rel=\"nofollow\" class=\"ap-connect-link\">959d9cbe748611e885bbbc305bf153a8</a>   <br />\n<a href=\"#!/hoffmanlab/segway/commits/1165847\" rel=\"nofollow\" class=\"ap-connect-link\">1165847</a> jt0.identifydir-seg.<a href=\"#!/hoffmanlab/segway/commits/959d9cbe748611e885bbbc305bf153a8\" rel=\"nofollow\" class=\"ap-connect-link\">959d9cbe748611e885bbbc305bf153a8</a>    <br />\n<a href=\"#!/hoffmanlab/segway/commits/1165846\" rel=\"nofollow\" class=\"ap-connect-link\">1165846</a> vit0.identifydir-seg.<a href=\"#!/hoffmanlab/segway/commits/959d9cbe748611e885bbbc305bf153a8\" rel=\"nofollow\" class=\"ap-connect-link\">959d9cbe748611e885bbbc305bf153a8</a>   <br />\n<a href=\"#!/hoffmanlab/segway/commits/1165847\" rel=\"nofollow\" class=\"ap-connect-link\">1165847</a> jt0.identifydir-seg.<a href=\"#!/hoffmanlab/segway/commits/959d9cbe748611e885bbbc305bf153a8\" rel=\"nofollow\" class=\"ap-connect-link\">959d9cbe748611e885bbbc305bf153a8</a>    </p>\n<p><a href=\"#!/hoffmanlab/segway/commits/1165847\" rel=\"nofollow\" class=\"ap-connect-link\">1165847</a> jt0.identifydir-seg.<a href=\"#!/hoffmanlab/segway/commits/959d9cbe748611e885bbbc305bf153a8\" rel=\"nofollow\" class=\"ap-connect-link\">959d9cbe748611e885bbbc305bf153a8</a>    gmtkJT  2   8000    <a href=\"#!/hoffmanlab/segway/commits/1104023552\" rel=\"nofollow\" class=\"ap-connect-link\">1104023552</a>.0000 2.2897  0<br />\n<a href=\"#!/hoffmanlab/segway/commits/1165846\" rel=\"nofollow\" class=\"ap-connect-link\">1165846</a> vit0.identifydir-seg.<a href=\"#!/hoffmanlab/segway/commits/959d9cbe748611e885bbbc305bf153a8\" rel=\"nofollow\" class=\"ap-connect-link\">959d9cbe748611e885bbbc305bf153a8</a>   <br />\n<a href=\"#!/hoffmanlab/segway/commits/1165846\" rel=\"nofollow\" class=\"ap-connect-link\">1165846</a> vit0.identifydir-seg.<a href=\"#!/hoffmanlab/segway/commits/959d9cbe748611e885bbbc305bf153a8\" rel=\"nofollow\" class=\"ap-connect-link\">959d9cbe748611e885bbbc305bf153a8</a>   gmtkViterbi 2   8000    <a href=\"#!/hoffmanlab/segway/commits/1823936512\" rel=\"nofollow\" class=\"ap-connect-link\">1823936512</a>.0000 2.0807  0</p>\n<p>Because Viterbi ran an extra time, its full log line appears after. This behaviour was happening in both python 2 and 3, I was never able to figure out why it only started now though and not before the conversion began.</p>", "type": "rendered"}, "created_on": "2018-06-22T19:56:12.494779+00:00", "user": {"display_name": "Matthew McNeil", "uuid": "{018cd21a-1658-4202-9b1e-99dabc3e14d0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B018cd21a-1658-4202-9b1e-99dabc3e14d0%7D"}, "html": {"href": "https://bitbucket.org/%7B018cd21a-1658-4202-9b1e-99dabc3e14d0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d7e7604c308bd957d77e1762b5caeddcd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMM-5.png"}}, "nickname": "mjmm13", "type": "user", "account_id": "5ac790531b5dd37ea53a123d"}, "inline": {"to": null, "from": null, "outdated": true, "path": "segway/cluster/__init__.py"}, "updated_on": "2018-06-22T19:56:12.501908+00:00", "type": "pullrequest_comment", "id": 67981192}