{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/89/comments/69946815.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/diff/mjmm13/segway_python23:c48413d9bb0d..50c798f683cf?path=segway%2Finput_master.py"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/89/_/diff#comment-69946815"}}, "parent": {"id": 69944600, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/89/comments/69944600.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/89/_/diff#comment-69944600"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 89, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/89.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/89"}}, "title": "Python 3 Compatibility"}, "content": {"raw": "In the util.py function save\\_substituted\\_resource the string function template.substitute is called. There is a line, `\"%s\" % w`, where w is the means calculation. This calls the \\_\\_str\\_ method, which will return unicode since bytes are incorrect in Python 3. The issue is that in Python 2 a check is done to see if the result of \\_\\_str\\_ is unicode, and will call it a second time if it is, this time changing the string it is being added to unicode as well \\(the \u201c%s\u201c in the above case\\).\n\nThis double calling is the only reason for the numbers to be different, the RNG did not come into play in this instance.", "markup": "markdown", "html": "<p>In the util.py function save_substituted_resource the string function template.substitute is called. There is a line, <code>\"%s\" % w</code>, where w is the means calculation. This calls the __str_ method, which will return unicode since bytes are incorrect in Python 3. The issue is that in Python 2 a check is done to see if the result of __str_ is unicode, and will call it a second time if it is, this time changing the string it is being added to unicode as well (the \u201c%s\u201c in the above case).</p>\n<p>This double calling is the only reason for the numbers to be different, the RNG did not come into play in this instance.</p>", "type": "rendered"}, "created_on": "2018-07-13T20:09:00.667359+00:00", "user": {"display_name": "Matthew McNeil", "uuid": "{018cd21a-1658-4202-9b1e-99dabc3e14d0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B018cd21a-1658-4202-9b1e-99dabc3e14d0%7D"}, "html": {"href": "https://bitbucket.org/%7B018cd21a-1658-4202-9b1e-99dabc3e14d0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d7e7604c308bd957d77e1762b5caeddcd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMM-5.png"}}, "nickname": "mjmm13", "type": "user", "account_id": "5ac790531b5dd37ea53a123d"}, "inline": {"to": null, "from": null, "outdated": true, "path": "segway/input_master.py"}, "updated_on": "2018-07-13T20:09:00.674824+00:00", "type": "pullrequest_comment", "id": 69946815}