{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/70/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/70.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/70/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/70/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/70/upon-bundling-segway-tries-to-reference-an"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/70/vote"}}, "reporter": {"display_name": "Rachel Chan", "uuid": "{20430f8d-4e6b-48cc-a8d8-c64868bf7e79}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D"}, "html": {"href": "https://bitbucket.org/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4397abec9f84e35f1f235b350984833dd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsRC-1.png"}}, "nickname": "rcwchan", "type": "user", "account_id": "557058:e439e22e-8cfc-4cf1-b090-030d33a0730e"}, "title": "Upon bundling, segway tries to reference an accumulator file for a run that was never queued in minibatch", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Upon bundling, segway tries to reference an accumulator file for a run that was never queued, in minibatch. I have reproduced this twice now. In both instances, segway attempted to look for an accumulator file that did not exist, and then errored out with the following:\r\n\r\n\r\n```\r\nException in thread Thread-1:\r\nTraceback (most recent call last):\r\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/threading.py\", line 551, in __bootstrap_inner\r\n    self.run()\r\n  File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 442, in run\r\n    self.result = self.runner.run_train_instance()\r\n  File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2113, in run_train_instance\r\n    round_index, kwargs)\r\n  File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2120, in progress_train_instance\r\n    self.run_train_round(self.instance_index, round_index, **kwargs)\r\n  File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2079, in run_train_round\r\n    restartable_jobs.wait()\r\n  File \"/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py\", line 289, in wait\r\n    self.process_job(jobid, job_info)\r\n  File \"/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py\", line 244, in process_job\r\n    (jobid, job_name, error_filename))\r\nRuntimeError: \r\nSubmitted Job (5700692) failed. Failed Job: emt0.0.bundle.K562_5_Track.traindir.d112e1a6280111e6b7f15254004fdc09.\r\nFor details, check error messages in /mnt/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160530_1458/results/20160601-1004/K562_5_Track.traindir/output/e/0/emt0.0.bundle.K562_5_Track.traindir.d112e1a6280111e6b7f15254004fdc09.\r\nSee the Troubleshooting section of the Segway documentation.\r\n```\r\n\r\n\r\n\r\n```\r\nError: Can't open file (/mnt/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160530_1458/results/20160601-1004/K562_5_Track.traindir/accumulators/acc.0.755.bin) for reading.\r\nError: Can't open file (/mnt/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160530_1458/results/20160601-1004/K562_5_Track.traindir/accumulators/acc.0.755.bin) for reading.\r\n```\r\n\r\nacc.0.755.bin does not exist in the accumulators folder. According to the jobs.tab, the job for the 755 window was never run, and according to the train log, it was never queued (which means minibatch did not choose it).\r\n\r\nCurrent theory is that minibatch does not choose this window, but for some reason, it gets chosen when the bundling job is run, and then segway cannot find it, so errors out.", "markup": "markdown", "html": "<p>Upon bundling, segway tries to reference an accumulator file for a run that was never queued, in minibatch. I have reproduced this twice now. In both instances, segway attempted to look for an accumulator file that did not exist, and then errored out with the following:</p>\n<div class=\"codehilite\"><pre><span></span>Exception in thread Thread-1:\nTraceback (most recent call last):\n  File &quot;/mnt/work1/software/python/2.7/lib/python2.7/threading.py&quot;, line 551, in __bootstrap_inner\n    self.run()\n  File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 442, in run\n    self.result = self.runner.run_train_instance()\n  File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 2113, in run_train_instance\n    round_index, kwargs)\n  File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 2120, in progress_train_instance\n    self.run_train_round(self.instance_index, round_index, **kwargs)\n  File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 2079, in run_train_round\n    restartable_jobs.wait()\n  File &quot;/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py&quot;, line 289, in wait\n    self.process_job(jobid, job_info)\n  File &quot;/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py&quot;, line 244, in process_job\n    (jobid, job_name, error_filename))\nRuntimeError: \nSubmitted Job (5700692) failed. Failed Job: emt0.0.bundle.K562_5_Track.traindir.d112e1a6280111e6b7f15254004fdc09.\nFor details, check error messages in /mnt/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160530_1458/results/20160601-1004/K562_5_Track.traindir/output/e/0/emt0.0.bundle.K562_5_Track.traindir.d112e1a6280111e6b7f15254004fdc09.\nSee the Troubleshooting section of the Segway documentation.\n</pre></div>\n\n\n<div class=\"codehilite\"><pre><span></span><span class=\"n\">Error</span><span class=\"o\">:</span> <span class=\"n\">Can</span><span class=\"s1\">&#39;t open file (/mnt/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160530_1458/results/20160601-1004/K562_5_Track.traindir/accumulators/acc.0.755.bin) for reading.</span>\n<span class=\"s1\">Error: Can&#39;</span><span class=\"n\">t</span> <span class=\"n\">open</span> <span class=\"n\">file</span> <span class=\"o\">(/</span><span class=\"n\">mnt</span><span class=\"sr\">/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160530_1458/results/20160601-1004/K562_5_Track.traindir/accumulators/</span><span class=\"n\">acc</span><span class=\"o\">.</span><span class=\"mf\">0.755</span><span class=\"o\">.</span><span class=\"na\">bin</span><span class=\"o\">)</span> <span class=\"k\">for</span> <span class=\"n\">reading</span><span class=\"o\">.</span>\n</pre></div>\n\n\n<p>acc.0.755.bin does not exist in the accumulators folder. According to the jobs.tab, the job for the 755 window was never run, and according to the train log, it was never queued (which means minibatch did not choose it).</p>\n<p>Current theory is that minibatch does not choose this window, but for some reason, it gets chosen when the bundling job is run, and then segway cannot find it, so errors out.</p>", "type": "rendered"}, "assignee": {"display_name": "Rachel Chan", "uuid": "{20430f8d-4e6b-48cc-a8d8-c64868bf7e79}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D"}, "html": {"href": "https://bitbucket.org/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4397abec9f84e35f1f235b350984833dd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsRC-1.png"}}, "nickname": "rcwchan", "type": "user", "account_id": "557058:e439e22e-8cfc-4cf1-b090-030d33a0730e"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2016-06-01T15:37:26.708562+00:00", "milestone": null, "updated_on": "2016-07-26T18:59:35.658258+00:00", "type": "issue", "id": 70}