{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/54/comments/19972925.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/diff/rcwchan/segway:None..None?path=segway%2Fcluster%2F__init__.py"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/54/_/diff#comment-19972925"}}, "parent": {"id": 19808997, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/54/comments/19808997.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/54/_/diff#comment-19808997"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 54, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/54.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/54"}}, "title": "Add job template deletion to cluster/common.py and cluster/__init__.py"}, "content": {"raw": "According to the documentation linked, ```RestartableJob.__del__()``` would only be called when the reference count of RestartableJob drops to 0, which is what we want (since RestartableJob is the only object that holds JobTemplateFactory, which is the only object that holds the job template). I don't think there would be a case where we would like to delete the job template even if there are other references to RestartableJob (though there shouldn't be). \n\nAlso, I tested on mordor and double deletion of a job template calls a double free, which results in a segfault (which can't be caught the same way as an exception).", "markup": "markdown", "html": "<p>According to the documentation linked, <code>RestartableJob.__del__()</code> would only be called when the reference count of RestartableJob drops to 0, which is what we want (since RestartableJob is the only object that holds JobTemplateFactory, which is the only object that holds the job template). I don't think there would be a case where we would like to delete the job template even if there are other references to RestartableJob (though there shouldn't be). </p>\n<p>Also, I tested on mordor and double deletion of a job template calls a double free, which results in a segfault (which can't be caught the same way as an exception).</p>", "type": "rendered"}, "created_on": "2016-06-20T15:15:45.873320+00:00", "user": {"display_name": "Rachel Chan", "uuid": "{20430f8d-4e6b-48cc-a8d8-c64868bf7e79}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D"}, "html": {"href": "https://bitbucket.org/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4397abec9f84e35f1f235b350984833dd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsRC-1.png"}}, "nickname": "rcwchan", "type": "user", "account_id": "557058:e439e22e-8cfc-4cf1-b090-030d33a0730e"}, "inline": {"to": null, "from": null, "outdated": false, "path": "segway/cluster/__init__.py"}, "updated_on": "2016-06-20T17:38:34.411075+00:00", "type": "pullrequest_comment", "id": 19972925}